@startuml "email-expiry-behavior"

title Email Expiry Behavior (current)

actor "Customer" as cx
participant "Account activation link" as link

group email <  7d old, invite < 60d old
	cx -> link: Click link
	link -> cx: Open account activation page
end group

group email > 7d old, invite < 60d old
	cx -> link: Click link
	link -> cx: Display "New activation email sent" message, and send email
end group

group email any age, invite > 60d old
	cx -> link: Click link
	link -> cx: Display "Invite expired" message
end group

@enduml
