@startuml "sales-proposed"
!pragma teoz true

title Account Activation Sequence Diagram (proposed sales flow)

actor "Customer" as cx
participant "DocuSign" as ds
participant "oat-spa" as oatspa
participant "Salesforce" as sf
participant "salesforce-sentinel" as sfs
queue Pulsar as ps
participant "consumer-user-emails" as cue
participant "toast-restaurants" as rx
participant "toast-users" as users
participant "SendGrid" as sg
participant "Customer Mailbox" as cxmbox
participant "ToastWeb" as tw

{start} cx -> ds: Complete TMA

group Account activation prereqs

	group Stage automation (details TBD)
		ds -> sf: Move Opp to Stage 11
		sf -> sfs: Move Opp to Stage 11
	end group

	group Restaurant create (details TBD)
		note right sfs
			more details at
			system-docs/platform/business-platform/restaurant-create
		end note
		sfs -> rx: Create restaurant
		rx -> tw: Create restaurant
		tw ->> ps: Emit RestaurantCreate message
	end group

	group User create (details TBD)
		sfs -> sfs: TBD
	end group

end group

par

group Redirect to account activation
	ds -> cx: Redirect to OAT SPA (param: envelope-id)
	cx -> oatspa: Intermediate OAT SPA (param: envelope-id)
	oatspa -> oatspa: Fetch Rx ID and User ID (details TBD)
	oatspa -> users: GET /api/activation-url?rxid=X&userid=Y
	users -> oatspa: Return Account Activation URL
	{end} oatspa -> cx: Redirect to Account Activation

	{start} <-> {end} : SLA TBD but must be good UX

	cx -> tw: Activate user account
end group

group Account activiation initial email
	sfs ->> ps: Emit InviteEmailEvent message (details TBD)
	ps ->> cue: Consume InviteEmailEvent message
	cue -> cue: Generate account activation email
	cue -> sg: Send account activation email
	sg -> cxmbox: Send account activation email
	cx -> cxmbox: Read account activation email
	cx -> tw: Activate user account
end group

end par

@enduml
